"""
ComfyUI APIMart image generation nodes.
Integrates Gemini and GPT-Image-2 generation nodes.
"""

from .gemini_node import (
    NODE_CLASS_MAPPINGS as GEMINI_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GEMINI_NODE_DISPLAY_NAME_MAPPINGS,
)
from .gpt_image_2_node import (
    NODE_CLASS_MAPPINGS as GPT_IMAGE_2_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE_2_NODE_DISPLAY_NAME_MAPPINGS,
)
from .gpt_image_2_official_node import (
    NODE_CLASS_MAPPINGS as GPT_IMAGE_2_OFFICIAL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE_2_OFFICIAL_NODE_DISPLAY_NAME_MAPPINGS,
)
from .reach_gpt_image2_node import (
    NODE_CLASS_MAPPINGS as REACH_GPT_IMAGE2_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REACH_GPT_IMAGE2_NODE_DISPLAY_NAME_MAPPINGS,
)
from .reach_gpt_image2_sync_node import (
    NODE_CLASS_MAPPINGS as REACH_GPT_IMAGE2_SYNC_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REACH_GPT_IMAGE2_SYNC_NODE_DISPLAY_NAME_MAPPINGS,
)
from .cpa_gpt_image2_node import (
    NODE_CLASS_MAPPINGS as CPA_GPT_IMAGE2_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CPA_GPT_IMAGE2_NODE_DISPLAY_NAME_MAPPINGS,
)
from .reach_nano_node import (
    NODE_CLASS_MAPPINGS as REACH_NANO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REACH_NANO_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **GEMINI_NODE_CLASS_MAPPINGS,
    **GPT_IMAGE_2_NODE_CLASS_MAPPINGS,
    **GPT_IMAGE_2_OFFICIAL_NODE_CLASS_MAPPINGS,
    **REACH_GPT_IMAGE2_NODE_CLASS_MAPPINGS,
    **REACH_GPT_IMAGE2_SYNC_NODE_CLASS_MAPPINGS,
    **CPA_GPT_IMAGE2_NODE_CLASS_MAPPINGS,
    **REACH_NANO_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GEMINI_NODE_DISPLAY_NAME_MAPPINGS,
    **GPT_IMAGE_2_NODE_DISPLAY_NAME_MAPPINGS,
    **GPT_IMAGE_2_OFFICIAL_NODE_DISPLAY_NAME_MAPPINGS,
    **REACH_GPT_IMAGE2_NODE_DISPLAY_NAME_MAPPINGS,
    **REACH_GPT_IMAGE2_SYNC_NODE_DISPLAY_NAME_MAPPINGS,
    **CPA_GPT_IMAGE2_NODE_DISPLAY_NAME_MAPPINGS,
    **REACH_NANO_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
