"""
ComfyUI APIMart image generation nodes.
Integrates Gemini and GPT-Image-2 generation nodes.
"""

from .gemini_node import (
    NODE_CLASS_MAPPINGS as GEMINI_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GEMINI_NODE_DISPLAY_NAME_MAPPINGS,
)
from .gpt_image_2_node import (
    NODE_CLASS_MAPPINGS as GPT_IMAGE_2_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE_2_NODE_DISPLAY_NAME_MAPPINGS,
)
from .gpt_image_2_official_node import (
    NODE_CLASS_MAPPINGS as GPT_IMAGE_2_OFFICIAL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE_2_OFFICIAL_NODE_DISPLAY_NAME_MAPPINGS,
)
from .xx_gpt_image_2_official_node import (
    NODE_CLASS_MAPPINGS as XX_GPT_IMAGE_2_OFFICIAL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as XX_GPT_IMAGE_2_OFFICIAL_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **GEMINI_NODE_CLASS_MAPPINGS,
    **GPT_IMAGE_2_NODE_CLASS_MAPPINGS,
    **GPT_IMAGE_2_OFFICIAL_NODE_CLASS_MAPPINGS,
    **XX_GPT_IMAGE_2_OFFICIAL_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GEMINI_NODE_DISPLAY_NAME_MAPPINGS,
    **GPT_IMAGE_2_NODE_DISPLAY_NAME_MAPPINGS,
    **GPT_IMAGE_2_OFFICIAL_NODE_DISPLAY_NAME_MAPPINGS,
    **XX_GPT_IMAGE_2_OFFICIAL_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
